### ISSUE TITLE
Remove imagePullSecrets mandatory

### ISSUE THREAD

**Issue by lucaspouzac** [deepgram/self-hosted-resources#14]
Remove imagePullSecrets mandatory in helm charts beacuse we used internal docker proxy cache which configure this secret

```
      imagePullSecrets:
      - name: {{ required "Missing image repository credentials - see `global.pullSecretRef`" .Values.global.pullSecretRef }}
```

**Comment by bd-g** [comment]
@lucaspouzac Thanks for the enhancement request! For tracking, could you include your Deepgram Project ID in the issue description? Thanks!
