### ISSUE TITLE
Broken Helm index

### ISSUE THREAD

**Issue by milosgajdos** [deepgram/self-hosted-resources#22]
## What is the current behavior?

Helm index is missing chart for self-hostedd setup

```shell
$ helm pull deepgram/deepgram-self-hosted
Error: chart "deepgram-self-hosted" matching  not found in deepgram index. (try 'helm repo update'): no chart version found for deepgram-self-hosted-
```

## Steps to reproduce

```shell
helm repo add deepgram https://deepgram.github.io/self-hosted-resources
helm update
helm pull deepgram/deepgram-self-hosted
```

## Expected behavior

`deepgram-self-hosted` should be downloaded to the local filesystem

## Please tell us about your environment
 macOS 14.4.1 (23E224)

**Comment by bd-g** [comment]
@milosgajdos As the Chart is currently on a beta release, you will need to specify the `--devel` flag. See the [Helm Docs](https://helm.sh/docs/helm/helm_install/) for more details on available flags. 

I'll keep this issue open until I can update the documentation to call this out explicitly.
